- name: C-bug
  description: "Category: bug"
  color: "B60205"
- name: C-refactor
  description: "Category: refactor"
  color: "B60205"
- name: C-cleanup
  description: "Category: cleanup"
  color: "B60205"
- name: C-documentation
  description: "Category: documentation"
  color: "B60205"
- name: C-feature
  description: "Category: feature"
  color: "B60205"
- name: A-tools/build
  description: "Area: build"
  color: "d7e102"
- name: E-renew2022
  description: "Epic: renewal 2022"
  color: "453A97"
