name: PRD
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"
      - name: install
        run: npm install
      - name: Can Publish
        run: npx can-npm-publish --verbose
      - name: typecheck
        run: npm run typecheck
      - name: lint
        run: npm run lint
      - name: format
        run: npm run format
      - name: test
        run: npm run test
      - name: build
        run: npm run build:stg
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
