
name: github-label-sync

on:
  push:
    # branches:
    #   - main
    paths:
      - .github/labels.yaml
      - .github/workflows/github-label-sync.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/github-label-sync-action
