name: lighthouse

on:
  schedule:
    - cron: "23 23 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lighthouse
        run: sudo npm i -g lighthouse
      - name: Run lighthouse
        run: |
          lighthouse \
            --chrome-flags="--headless" \
            --output html --output-path /tmp/report.html \
            'https://blog.ojisan.io/'
          mkdir ./result
          cp /tmp/report.html ./result/report.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
          keep_files: true
